# -*- coding: utf-8 -*-
"""20230913_4120E013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FR1BOAh7Fopqd66NF5XQJ9ITvDooOnMl
"""

3**211