# -*- coding: utf-8 -*-
"""20230913_4120E013_power.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okl5lLoOSCSA5TVOWfkBQh7FHAzb6Ygt
"""

a=int(input('enter nuber A : '))
b=int(input('enter nuber B : '))
print('A^b = ',a**b)