# -*- coding: utf-8 -*-
"""20230913_4120E013_enter your name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geros24pXwjR-wGDE_Hvx7ViTwBLOKA8
"""

x = input('Enter your name:')
print('Hello, ' + x)