# -*- coding: utf-8 -*-
"""20230913_4120E013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uktShxH92HfdCJYHwTrNniaR0U8QPOqw
"""

3**21